
import java.awt.Color;
import java.awt.Point;
import javax.swing.UIManager;
import mdlaf.MaterialLookAndFeel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SH Utso
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    int posX=0,posY=0;
    
    public StartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObjectContainer = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        ExitBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        ExitBtn2 = new javax.swing.JButton();
        BG1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setName("StartFrame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 650));
        getContentPane().setLayout(new java.awt.CardLayout());

        ObjectContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBtn.setBackground(new java.awt.Color(44, 62, 80));
        ExitBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(236, 240, 241));
        ExitBtn.setText("Exit");
        ExitBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ExitBtn.setBorderPainted(false);
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitBtnMousePressed(evt);
            }
        });
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        ObjectContainer.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Please login or register");
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 50));
        ObjectContainer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Welcome");
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 60));
        ObjectContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(250, 30));
        ObjectContainer.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 260, 250, -1));

        jButton2.setBackground(new java.awt.Color(44, 62, 80));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(236, 240, 241));
        jButton2.setText("Register");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(250, 30));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ObjectContainer.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, -1, -1));

        jButton1.setBackground(new java.awt.Color(44, 62, 80));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(236, 240, 241));
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 30));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ObjectContainer.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 310, -1, -1));

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(236, 240, 241));
        jTextField1.setText("Username");
        jTextField1.setToolTipText("");
        jTextField1.setPreferredSize(new java.awt.Dimension(250, 30));
        ObjectContainer.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 210, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        BG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BGMouseDragged(evt);
            }
        });
        BG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BGMousePressed(evt);
            }
        });
        ObjectContainer.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(ObjectContainer, "card2");

        RegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBtn1.setBackground(new java.awt.Color(44, 62, 80));
        ExitBtn1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ExitBtn1.setForeground(new java.awt.Color(236, 240, 241));
        ExitBtn1.setText("Back");
        ExitBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ExitBtn1.setBorderPainted(false);
        ExitBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn1.setPreferredSize(new java.awt.Dimension(100, 30));
        ExitBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitBtn1MousePressed(evt);
            }
        });
        ExitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn1ActionPerformed(evt);
            }
        });
        RegisterPanel.add(ExitBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Enter your informations correctly");
        jLabel3.setPreferredSize(new java.awt.Dimension(400, 50));
        RegisterPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Registration");
        jLabel4.setPreferredSize(new java.awt.Dimension(250, 60));
        RegisterPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 340, -1));

        jPasswordField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField2.setPreferredSize(new java.awt.Dimension(250, 30));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        RegisterPanel.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 340, 250, -1));

        jButton3.setBackground(new java.awt.Color(44, 62, 80));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(236, 240, 241));
        jButton3.setText("Confirm");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(250, 30));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        RegisterPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 450, -1, -1));

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2.setText("Username");
        jTextField2.setToolTipText("");
        jTextField2.setPreferredSize(new java.awt.Dimension(250, 30));
        RegisterPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 180, -1, -1));

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(236, 240, 241));
        jTextField3.setText("Email");
        jTextField3.setToolTipText("");
        jTextField3.setPreferredSize(new java.awt.Dimension(250, 30));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        RegisterPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 220, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 30));
        RegisterPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 260, 150, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Enter your password");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 30));
        RegisterPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 310, 250, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Gender");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 30));
        RegisterPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Confirm password");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 30));
        RegisterPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 370, 250, -1));

        jPasswordField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField3.setPreferredSize(new java.awt.Dimension(250, 30));
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        RegisterPanel.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 400, 250, -1));

        ExitBtn2.setBackground(new java.awt.Color(44, 62, 80));
        ExitBtn2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ExitBtn2.setForeground(new java.awt.Color(236, 240, 241));
        ExitBtn2.setText("Exit");
        ExitBtn2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ExitBtn2.setBorderPainted(false);
        ExitBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn2.setPreferredSize(new java.awt.Dimension(100, 30));
        ExitBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtn2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitBtn2MousePressed(evt);
            }
        });
        ExitBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn2ActionPerformed(evt);
            }
        });
        RegisterPanel.add(ExitBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 550, -1, -1));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        BG1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BG1MouseDragged(evt);
            }
        });
        BG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BG1MousePressed(evt);
            }
        });
        RegisterPanel.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(RegisterPanel, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        ExitBtn.setBackground(new Color(52,73,94));
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        ExitBtn.setBackground(new Color(44,62,80));
    }//GEN-LAST:event_ExitBtnMouseExited

    private void ExitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMousePressed
        ExitBtn.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_ExitBtnMousePressed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(52,73,94));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String a = jTextField1.getText();
        String b = jPasswordField1.getText();
        
        if( a.equals("root") && b.equals("root")){
            this.dispose();
            new LoginPage().show();
        }
        
        else{
            new Wrong().show();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(44,62,80));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(new Color(52,73,94));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(new Color(44,62,80));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ObjectContainer.setVisible(false);
        RegisterPanel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jButton1.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        jButton2.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jButton2MousePressed

    private void BGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMouseDragged
        Point currCoords = evt.getLocationOnScreen();
            setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_BGMouseDragged

    private void BGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMousePressed
       posX=evt.getX();
       posY=evt.getY();
    }//GEN-LAST:event_BGMousePressed

    private void ExitBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn1MouseEntered
        ExitBtn1.setBackground(new Color(52,73,94));
    }//GEN-LAST:event_ExitBtn1MouseEntered

    private void ExitBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn1MouseExited
        ExitBtn1.setBackground(new Color(44,62,80));
    }//GEN-LAST:event_ExitBtn1MouseExited

    private void ExitBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn1MousePressed
        ExitBtn1.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_ExitBtn1MousePressed

    private void ExitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn1ActionPerformed
        ObjectContainer.setVisible(true);
        RegisterPanel.setVisible(false);
    }//GEN-LAST:event_ExitBtn1ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(new Color(52,73,94));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new Color(44,62,80));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        jButton3.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BG1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG1MouseDragged
        Point currCoords = evt.getLocationOnScreen();
            setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_BG1MouseDragged

    private void BG1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG1MousePressed
        posX=evt.getX();
       posY=evt.getY();
    }//GEN-LAST:event_BG1MousePressed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void ExitBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn2MouseEntered
        ExitBtn2.setBackground(new Color(52,73,94));
    }//GEN-LAST:event_ExitBtn2MouseEntered

    private void ExitBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn2MouseExited
        ExitBtn2.setBackground(new Color(44,62,80));
    }//GEN-LAST:event_ExitBtn2MouseExited

    private void ExitBtn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtn2MousePressed
        ExitBtn2.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_ExitBtn2MousePressed

    private void ExitBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel (new MaterialLookAndFeel ());
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BG1;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton ExitBtn1;
    private javax.swing.JButton ExitBtn2;
    private javax.swing.JPanel ObjectContainer;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
